language: node_js
node_js:
- "7"

script: npm run build

deploy:
  fqdn: hyperapp.deployable.site
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
